# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ScreenBroadcastUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ScreenBroadcastForm(object):
    def setupUi(self, ScreenBroadcastForm):
        ScreenBroadcastForm.setObjectName("ScreenBroadcastForm")
        ScreenBroadcastForm.resize(600, 65)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Core/Core/Logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        ScreenBroadcastForm.setWindowIcon(icon)
        self.main_layout = QtWidgets.QVBoxLayout(ScreenBroadcastForm)
        self.main_layout.setContentsMargins(0, 0, 0, 0)
        self.main_layout.setSpacing(0)
        self.main_layout.setObjectName("main_layout")
        self.main_container = QtWidgets.QWidget(ScreenBroadcastForm)
        self.main_container.setObjectName("main_container")
        self.main_container_layout = QtWidgets.QVBoxLayout(self.main_container)
        self.main_container_layout.setContentsMargins(0, 0, 0, 0)
        self.main_container_layout.setSpacing(0)
        self.main_container_layout.setObjectName("main_container_layout")
        self.title_label = QtWidgets.QLabel(self.main_container)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.title_label.setFont(font)
        self.title_label.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(82, 229, 231, 255), stop:1 rgba(19, 12, 183, 255));\n"
"color: rgb(255, 255, 255);")
        self.title_label.setAlignment(QtCore.Qt.AlignCenter)
        self.title_label.setObjectName("title_label")
        self.main_container_layout.addWidget(self.title_label)
        self.tool_buttons_layout = QtWidgets.QHBoxLayout()
        self.tool_buttons_layout.setContentsMargins(5, 3, 5, 5)
        self.tool_buttons_layout.setSpacing(3)
        self.tool_buttons_layout.setObjectName("tool_buttons_layout")
        self.window_broadcast = QtWidgets.QPushButton(self.main_container)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.window_broadcast.sizePolicy().hasHeightForWidth())
        self.window_broadcast.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.window_broadcast.setFont(font)
        self.window_broadcast.setCheckable(True)
        self.window_broadcast.setObjectName("window_broadcast")
        self.tool_buttons_layout.addWidget(self.window_broadcast)
        self.hide_toolbar = QtWidgets.QPushButton(self.main_container)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.hide_toolbar.sizePolicy().hasHeightForWidth())
        self.hide_toolbar.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.hide_toolbar.setFont(font)
        self.hide_toolbar.setObjectName("hide_toolbar")
        self.tool_buttons_layout.addWidget(self.hide_toolbar)
        self.stop_broadcast = QtWidgets.QPushButton(self.main_container)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stop_broadcast.sizePolicy().hasHeightForWidth())
        self.stop_broadcast.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.stop_broadcast.setFont(font)
        self.stop_broadcast.setObjectName("stop_broadcast")
        self.tool_buttons_layout.addWidget(self.stop_broadcast)
        self.tool_buttons_layout.setStretch(0, 1)
        self.tool_buttons_layout.setStretch(1, 1)
        self.tool_buttons_layout.setStretch(2, 1)
        self.main_container_layout.addLayout(self.tool_buttons_layout)
        self.main_layout.addWidget(self.main_container)

        self.retranslateUi(ScreenBroadcastForm)
        self.window_broadcast.clicked['bool'].connect(ScreenBroadcastForm.toggle_window_broadcast) # type: ignore
        self.hide_toolbar.clicked.connect(ScreenBroadcastForm.hide_toolbar) # type: ignore
        self.stop_broadcast.clicked.connect(ScreenBroadcastForm.stop_broadcast) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(ScreenBroadcastForm)

    def retranslateUi(self, ScreenBroadcastForm):
        ScreenBroadcastForm.setWindowTitle("屏幕广播")
        self.title_label.setText("PYCM 控制台 - 屏幕广播")
        self.window_broadcast.setText("窗口广播")
        self.hide_toolbar.setText("隐藏工具栏")
        self.stop_broadcast.setText("结束广播")
from Resources import Resources
