# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AboutUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AboutDialog(object):
    def setupUi(self, AboutDialog):
        AboutDialog.setObjectName("AboutDialog")
        AboutDialog.resize(487, 280)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(AboutDialog.sizePolicy().hasHeightForWidth())
        AboutDialog.setSizePolicy(sizePolicy)
        AboutDialog.setMinimumSize(QtCore.QSize(0, 0))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Core/Core/Logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        AboutDialog.setWindowIcon(icon)
        self.main_layout = QtWidgets.QVBoxLayout(AboutDialog)
        self.main_layout.setContentsMargins(25, 20, 25, 20)
        self.main_layout.setObjectName("main_layout")
        self.title_layout = QtWidgets.QVBoxLayout()
        self.title_layout.setSpacing(0)
        self.title_layout.setObjectName("title_layout")
        self.product_name = QtWidgets.QLabel(AboutDialog)
        font = QtGui.QFont()
        font.setFamily("阿里巴巴普惠体")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.product_name.setFont(font)
        self.product_name.setAlignment(QtCore.Qt.AlignCenter)
        self.product_name.setObjectName("product_name")
        self.title_layout.addWidget(self.product_name)
        self.buildInfo = QtWidgets.QLabel(AboutDialog)
        font = QtGui.QFont()
        font.setFamily("阿里巴巴普惠体")
        self.buildInfo.setFont(font)
        self.buildInfo.setAlignment(QtCore.Qt.AlignCenter)
        self.buildInfo.setObjectName("buildInfo")
        self.title_layout.addWidget(self.buildInfo)
        self.project_home = QtWidgets.QLabel(AboutDialog)
        font = QtGui.QFont()
        font.setFamily("阿里巴巴普惠体")
        self.project_home.setFont(font)
        self.project_home.setText("<html><head/><body><p><a href=\"https://www.ylwxfw.cn\"><span style=\" text-decoration: underline; color:#0000ff;\">https://www.ylwxfw.cn</span></a></p></body></html>")
        self.project_home.setAlignment(QtCore.Qt.AlignCenter)
        self.project_home.setOpenExternalLinks(True)
        self.project_home.setObjectName("project_home")
        self.title_layout.addWidget(self.project_home)
        self.thank_info = QtWidgets.QLabel(AboutDialog)
        self.thank_info.setText("广西聚本教育科技有限公司")
        self.thank_info.setAlignment(QtCore.Qt.AlignCenter)
        self.thank_info.setOpenExternalLinks(True)
        self.thank_info.setObjectName("thank_info")
        self.title_layout.addWidget(self.thank_info)
        self.main_layout.addLayout(self.title_layout)
        self.operation_buttons = QtWidgets.QDialogButtonBox(AboutDialog)
        self.operation_buttons.setOrientation(QtCore.Qt.Horizontal)
        self.operation_buttons.setStandardButtons(QtWidgets.QDialogButtonBox.Ok)
        self.operation_buttons.setCenterButtons(True)
        self.operation_buttons.setObjectName("operation_buttons")
        self.main_layout.addWidget(self.operation_buttons)

        self.retranslateUi(AboutDialog)
        self.operation_buttons.accepted.connect(AboutDialog.accept) # type: ignore
        self.operation_buttons.rejected.connect(AboutDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(AboutDialog)

    def retranslateUi(self, AboutDialog):
        AboutDialog.setWindowTitle("关于")
        self.product_name.setText("PYCM 客户端")
        self.buildInfo.setText("无构建信息")
        self.operation_buttons.button(QtWidgets.QDialogButtonBox.Ok).setText("确定")
from Resources import Resources
